name: lattice_env

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - conda-forge::numpy=1.26.*
  - fpylll
  - pytorch::pytorch
  - pytorch-cuda=11.8
  - torchmetrics
  - pip
  - pip:
    - einops
    - estimator
    - joblib
    - matplotlib
    - pandas
    - polars
    - scikit-learn
    - scipy
    - tabulate
    - tqdm
    - wandb
    - chardet